package com.alumThy.alumnosThy.reposity;

import org.springframework.data.jpa.repository.JpaRepository;

import com.alumThy.alumnosThy.model.alumnosModel;

/*
 * ESTA INTERFAZ EXTIENDE DE JPAREPOSITORIO, CONTIENE TODOS LOS METODOS 
 * NECESARIOS DE UN CRUD, ES MAS COMPLETO DE CRUD REPOSITORIO,
 * SON INTERFAZ QUE SON UTILIZADAS PARA INTERACTUAR CON BASES DE DATOS Y REALIZAR 
 * OPERACIONES CRUD (CREAR, LEER, ACTUALIZAR, ELIMINAR) SOBRE ENTIDADES.
 */
public interface alumnosRepositorio extends JpaRepository<alumnosModel, Long>{

	/*
	 * JPAREPOSITORY EXTIENDE CRUDREPOSITORY Y AGREGA FUNCIONALIDADES MAS AVANZADAS 
	 * ESPECIFICAS DE JPA(JAVA PERSISTENCE API). HEREDA TODOS LOS METODOS DE CRUDREPOSITORY.
	 */
}
